version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 50M # Limit frontend to 50MB of memory

  backend:
    image: backend:latest # Use the pre-built Docker image
    ports:
      - "9000:9000"
    environment:
      SCALA_BACKEND_CONFIG: "production" # Set your environment variables here
      JAVA_OPTS: "-Xms128M -Xmx256M -XX:+UseG1GC" 
    deploy:
      resources:
        limits:
          memory: 450M # Limit backend to 450MB of memory
    networks:
      - poker-network

networks:
  poker-network:
    driver: bridge
